rly_file = "Wolverhampton.rly"
ttb_files = [ "Wolverhampton_March_28_2025_0600.ttb",]
img_files = [ "Wolverhampton.bmp",]
doc_files = [ "README.md",]
ssn_files = [ "Wolverhampton_March_28_March_2025_0600.ssn",]
release_date = "2025-03-31"
version = "1.0.1"
country_code = "GB"
factual = true
description = "Simulation of Wolverhampton, UK in March 2025"
year = 2025
display_name = "Wolverhampton"
name = "Wolverhampton"
signal_position = "left"
author = "Krizar"
contributors = []
